### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by sebszocinski** [vinkla/autocomplete-tailwind#4]
I installed this but it doesn't seem to show up in my autocomplete list...?

I'm using Pug but i've also tested it on .html files and no dice.

Is there any way we can debug this?

**Comment by vinkla** [comment]
Thanks for reporting! It should work fine in HTML. It uses the [`.meta.attribute-with-value.class.html`](https://github.com/vinkla/autocomplete-tailwind/blob/de9bd87b6073d597df61d1071ef1b911811561eb/src/provider.js#L6) selector.

I haven't tried it myself in Pug files. Maybe you could submit a snippet of code you're trying?

Do you get any error messages in Atom's console? You can open it using <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>I</kbd>.

**Comment by sebszocinski** [comment]
Hi @vinkla thanks for the reply.

I just tried again with a fresh install of Atom and I get nothing appearing in my autocomplete menu.

I'm trying your screenshot example of `bg-in` which should show the same list of colours for backgrounds as in your screenshot but instead I just get this...

![image](https://user-images.githubusercontent.com/5466694/54329388-657d6700-4661-11e9-8127-39c6192d01f6.png)
![image](https://user-images.githubusercontent.com/5466694/54329425-8645bc80-4661-11e9-9abe-4a7c376176c9.png)

Am I missing something? does this require any other plugins or settings?

**Comment by sebszocinski** [comment]
Also, no errors in console either, just checked.

**Comment by vinkla** [comment]
Just tried it myself and I'm having issues when I create a new file. Though, when I close it and open it up again it seems to work.

What we want is to autocomplete the following syntax:

```scss
class="" // HTML
className="" // JSX
```

Today we've using the `.meta.attribute-with-value.class.html` which works fine in HTML, PHP and Ruby files containing HTML.

Maybe we could ask @Aerijo who is a grammar ninja? Do you have time to point us in the right direction?

**Comment by Aerijo** [comment]
@vinkla Looks like a Tree-sitter issue; the scopes aren't as detailed as they were before
https://github.com/atom/language-html/blob/master/grammars/tree-sitter-html.cson

**Comment by vinkla** [comment]
Thanks @Aerijo! I'll probably just use `.string.quoted` instead.

**Comment by vinkla** [comment]
Yeah, you're right. I solved it by using `.string.quoted` since we need to support PHP, HTML, Ruby, JSX, etc and added a check whether the line contains the `class|className` attribute.

**Comment by vinkla** [comment]
@sebszocinski I've published a new version. Please update and see if it works.

**Comment by sebszocinski** [comment]
Hi @vinkla thanks for the replies. 

I just updated and tried again and it's still not working for me? I even did a fresh Atom install (deleted .atom folder) and installed just the one package and it's still not working for me :/

**Comment by sebszocinski** [comment]
Ok interestingly it's working for `.php` files but not `.html` ?

**Comment by vinkla** [comment]
I've pushed an update for `.pug` in: 41178fde56e515ee77a9861b990bd423d7dbe5ec

Please download the latest version and try again.

**Comment by sebszocinski** [comment]
@vinkla Thank you that is great, I wonder if its possible to do the same for `.sass` files so we can have autocompletion in there too? i'm finding myself creating components in my sass files which requires moving tailwind classes over but occasionally I want to add new ones directly in the `.sass` file so having auto-completion there would be great.

**Comment by vinkla** [comment]
Great idea @sebszocinski! I've opened a new issue: #5

**Comment by sebszocinski** [comment]
Great thanks @vinkla — hopefully it's not a difficult feature to add in!

**Comment by limitlessloop** [comment]
> Ok interestingly it's working for `.php` and `.pug` files but not `.html` ?
> 
> Also, not sure if this can be fixed, but with pug you don't need to use `class="xxxx"` syntax and instead you can shorten to `div.className.classNameEtc` but currently that does not get picked up with the tailwind suggestions and I assume this is because `string.quoted` and searching for `class|className`?

Hi, I'm getting a similar issue to the above.

Autocomplete works when I create a php file, but when I create a html file no autocomplete options for tailwind appear. Any ideas what could be wrong?

**Comment by vinkla** [comment]
> Autocomplete works when I create a php file, but when I create a html file no autocomplete options for tailwind appear. Any ideas what could be wrong?

Double check that the syntax is set to HTML and try closing and open the file.

**Comment by limitlessloop** [comment]
Hi, I've tried opening and closing the file and atom. The syntax is definitely set to HTML. In fact, if I change the syntax to PHP it works, but obviously is the wrong syntax for the file.

**Comment by limitlessloop** [comment]
Not sure if it's of any use. But if I add `.text.html.basic` to the selector it works for me.

**Comment by vinkla** [comment]
Tried this locally and the autocompletion doesn't work when I create a new HTML file. When I close and reopen the file it seems to work again. What is weird is that it return different scopes:

```html
<body class="(cursor here)">
```

When the HTML file is first created and I run `Editor: Log Cursor Scopes` it returns:

```
text.html.basic
source.html
```

Then when I close and reopen the file it instead returns the following scopes:

```
text.html.basic
meta.tag.structure.body.html
meta.attribute-with-value.class.html
string.quoted.double.html
punctuation.definition.string.end.html
```

Not really sure why it returns different scopes at different states. Maybe @Aerijo can shed light on this scope behaviour in Atom? 

Adding `.text.html.basic` to the selector seems to make it work. I'll push an update with the updated selector. Thanks for reporting @limitlessloop!
